### ISSUE TITLE
Any way to contribute initially?

### ISSUE THREAD

**Issue by mooyg** [cap-so/cap#1]
I wonder if there is anyway to contribute to the project initially would love to know more :)

**Comment by Lakszy** [comment]
**+1**

I'm interested in exploring opportunities to contribute to the project and would appreciate any additional information you can provide.

**Comment by richiemcilroy** [comment]
Hey guys, thank you for showing interest! It's much appreciated. The repo will be updated later today with the first part of the monorepo (using Turborepo). Cheers!
