### ISSUE TITLE
Suggestion: The Readme is not up to date.

### ISSUE THREAD

**Issue by Lakszy** [cap-so/cap#3]
The ReadMe lacks essential details about the project's motive, vision, and end goal, making it outdated and potentially confusing for users and contributors. We need to update the ReadMe to include this crucial information.

**Proposed Changes:**

1. Clearly state the project's motive.
2. Define the long-term vision.
3. Outline the ultimate end goal.

**Comment by richiemcilroy** [comment]
Thank you @Lakszy - I agree. 

Making some updates shortly :)
